# @author Luchaoxin
# @version V 1.0
version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    restart: always
    volumes:
      - ./conf/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./conf/rules/node_status.yml:/etc/prometheus/node_status.yml
      - ./data/prometheus-data:/prometheus
    ports:
      - 9090:9090
      # - 11001:9090
    networks:
      - pistonint-framework-net

   alertmanager:
     image: prom/alertmanager
     container_name: alertmanager
     hostname: alertmanager
     restart: always
     volumes:
       - ./conf/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
     ports:
       - 9094:9093
     networks:
       - pistonint-framework-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    restart: always
    user: root
    volumes: 
      - ./data/grafana-data:/var/lib/grafana
      # - ./data/grafana-etc:/etc/grafana/
    ports:
      - 11005:3000
    networks:
      - pistonint-framework-net

  node-exporter:
    image: quay.io/prometheus/node-exporter
    container_name: node-exporter
    hostname: node-exporter
    restart: always
    ports:
      - 9100:9100
    networks:
      - pistonint-framework-net

  cadvisor:
    # image: google/cadvisor:latest
    image: lagoudocker/cadvisor:v0.37.0
    container_name: cadvisor
    hostname: cadvisor
    restart: always
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /var/run:/var/run:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /cgroup:/cgroup:ro
      - /sys/fs/cgroup/cpu,cpuacct:/sys/fs/cgroup/cpuacct,cpu 
    ports:
      - 9083:8080
    networks:
      - pistonint-framework-net

  blackbox-exporter:
    image: prom/blackbox-exporter:master
    container_name: blackbox-exporter
    hostname: blackbox-exporter
    restart: always
    volumes:
      - ./conf/blackbox-exporter:/etc/blackbox_exporter
    ports:
      - 9115:9115
    networks:
      - pistonint-framework-net
      
networks:
  pistonint-framework-net:
    external: true