# @author Luchaoxin
# @version V 1.0

version: '3.8'

services:
  mongodb:
    image: docker.io/mongo:4.2
    command: mongod --storageEngine wiredTiger --noscripting
    user: mongodb
    ports:
      - 27017:27017
    environment:
      TZ: Asia/Shanghai
    networks:
      - pistonint-framework-net

  policies:
    image: docker.io/eclipse/ditto-policies:${DITTO_VERSION:-latest}
    mem_limit: 384m
    env_file:
      - ./dev.env
    environment:
      #      - MONGO_DB_URI=
      - OPENJ9_JAVA_OPTIONS=-XX:+ExitOnOutOfMemoryError -Xtune:virtualized -Xss512k -XX:MaxRAMPercentage=80 -Dakka.coordinated-shutdown.exit-jvm=on -Dakka.cluster.shutdown-after-unsuccessful-join-seed-nodes=120s
      - MONGO_DB_HOSTNAME=mongodb
    # Set additional configuration options here
    # -Dditto.policies...
    command: java -jar starter.jar
    networks:
      - pistonint-framework-net

  things:
    image: docker.io/eclipse/ditto-things:${DITTO_VERSION:-latest}
    mem_limit: 384m
    depends_on:
      - policies
    env_file:
      - ./dev.env
    environment:
      - OPENJ9_JAVA_OPTIONS=-XX:+ExitOnOutOfMemoryError -Xtune:virtualized -Xss512k -XX:MaxRAMPercentage=80 -Dakka.coordinated-shutdown.exit-jvm=on -Dakka.cluster.shutdown-after-unsuccessful-join-seed-nodes=120s
      - MONGO_DB_HOSTNAME=mongodb
    # Set additional configuration options here
    # -Dditto.things...
    command: java -jar starter.jar
    networks:
      - pistonint-framework-net

  things-search:
    image: docker.io/eclipse/ditto-things-search:${DITTO_VERSION:-latest}
    mem_limit: 384m
    depends_on:
      - policies
    env_file:
      - ./dev.env
    environment:
      - OPENJ9_JAVA_OPTIONS=-XX:+ExitOnOutOfMemoryError -Xtune:virtualized -Xss512k -XX:MaxRAMPercentage=80 -Dakka.coordinated-shutdown.exit-jvm=on -Dakka.cluster.shutdown-after-unsuccessful-join-seed-nodes=120s
      - MONGO_DB_HOSTNAME=mongodb
    # Set additional configuration options here
    # -Dditto.things-search...
    command: java -jar starter.jar
    networks:
      - pistonint-framework-net

  concierge:
    image: docker.io/eclipse/ditto-concierge:${DITTO_VERSION:-latest}
    mem_limit: 384m
    depends_on:
      - policies
    env_file:
      - ./dev.env
    environment:
      - OPENJ9_JAVA_OPTIONS=-XX:+ExitOnOutOfMemoryError -Xtune:virtualized -Xss512k -XX:MaxRAMPercentage=80 -Dakka.coordinated-shutdown.exit-jvm=on -Dakka.cluster.shutdown-after-unsuccessful-join-seed-nodes=120s
      - MONGO_DB_HOSTNAME=mongodb
    # Set additional configuration options here
    # -Dditto.concierge...
    command: java -jar starter.jar
    networks:
      - pistonint-framework-net

  connectivity:
    image: docker.io/eclipse/ditto-connectivity:${DITTO_VERSION:-latest}
    mem_limit: 384m
    depends_on:
      - policies
      - concierge
    env_file:
      - ./dev.env
    environment:
      - OPENJ9_JAVA_OPTIONS=-XX:+ExitOnOutOfMemoryError -Xtune:virtualized -Xss512k -XX:MaxRAMPercentage=80 -Dakka.coordinated-shutdown.exit-jvm=on -Dakka.cluster.shutdown-after-unsuccessful-join-seed-nodes=120s
      - MONGO_DB_HOSTNAME=mongodb
    # Set additional configuration options here
    # -Dditto.connectivity...
    command: java -jar starter.jar
    networks:
      - pistonint-framework-net

  gateway:
    image: docker.io/eclipse/ditto-gateway:${DITTO_VERSION:-latest}
    mem_limit: 384m
    depends_on:
      - policies
      - concierge
    ports:
      - "8081:8080"
    env_file:
      - ./dev.env
    environment:
      - ENABLE_PRE_AUTHENTICATION=true
      - OPENJ9_JAVA_OPTIONS=-XX:+ExitOnOutOfMemoryError -Xtune:virtualized -Xss512k -XX:MaxRAMPercentage=80 -Dakka.coordinated-shutdown.exit-jvm=on -Dakka.cluster.shutdown-after-unsuccessful-join-seed-nodes=120s
      # You may use the environment for setting the devops password
      #- DEVOPS_PASSWORD=foobar
    # Set additional configuration options here
    # -Dditto.gateway...
    # Setting the devops password via java VM environment
    command: java -Dditto.gateway.authentication.devops.password=foobar -jar starter.jar
    networks:
      - pistonint-framework-net

  swagger-ui:
    image: docker.io/swaggerapi/swagger-ui:v3.38.0
    volumes:
      - ../../documentation/src/main/resources/openapi:/usr/share/nginx/html/openapi:ro
      - ../../documentation/src/main/resources/images:/usr/share/nginx/html/images:ro
      - ./swagger3-index.html:/usr/share/nginx/html/index.html:ro
    command: nginx -g 'daemon off;'

  nginx:
    image: docker.io/nginx:1.19-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx.htpasswd:/etc/nginx/nginx.htpasswd:ro
      - ./nginx-cors.conf:/etc/nginx/nginx-cors.conf:ro
      - ./index.html:/etc/nginx/html/index.html:ro
      - ../../documentation/src/main/resources/images:/etc/nginx/html/images:ro
    ports:
      - "${DITTO_EXTERNAL_PORT:-8080}:80"
    depends_on:
      - gateway
      - swagger-ui
    networks:
      - pistonint-framework-net

networks:
  pistonint-framework-net:
    external: true