# 使用说明
# 1. 使用docker-compose  宿主机不需要配置host来发现
# 2. 无需修改源码，根目录  docker-compose up 即可
# 3. 静静等待服务启动

version: '3.8'
services:

  redis:
    build:
      context: ./
      dockerfile: ./DockerfileWithFilter
    image: redis
    container_name: redis
    restart: always
    user: root
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/:/data
    ports:
      - "6379:6379"
    networks:
      - pistonint-framework-net

networks:
  pistonint-framework-net:
    external: true